package com.example.eventmaster;

import android.graphics.Bitmap;
import android.graphics.Color;
import android.net.Uri;
import android.os.Bundle;
import android.util.Log;
import android.widget.CompoundButton;
import android.widget.ImageView;
import android.widget.Switch;
import android.widget.TextView;
import android.widget.Toast;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;

public class ProfileActivity extends AppCompatActivity {
    private TextView displayName;
    private TextView displayEmail;
    private TextView displayPhoneNumber;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.profile_screen);

        displayName = findViewById(R.id.profile_name);
        displayEmail = findViewById(R.id.profile_email);
        displayPhoneNumber = findViewById(R.id.profile_phone_number);

        Profile user = (Profile) getIntent().getSerializableExtra("User"); // user from MainActivity

        // Makes autogenerated profile picture
        Bitmap pfpBitmap = Image.generateProfilePicture(user.getName(), 200, Color.parseColor("#3351A6"), Color.WHITE);
        // Grabs URI of saved profile picture image
        Uri savedUri = ProfilePicture.saveProfilePicture(this, pfpBitmap, user.getName());

        ImageView profile_picture = findViewById(R.id.profile_picture );
        // Sets the profile picture as the auto generated photo
        profile_picture.setImageBitmap(pfpBitmap);

        displayName.setText(user.getName());
        displayEmail.setText(user.getEmail());
        displayPhoneNumber.setText(user.getPhone_number());

    }
}
